Wait for all workers in backup inttest
Fixes test failures like this:

    backup_test.go:112:
        	Error Trace:	/home/runner/work/k0s/k0s/inttest/backup/backup_test.go:112
        	            				/opt/hostedtoolcache/go/1.25.4/x64/src/runtime/asm_amd64.s:1693
        	Error:      	Not equal:
        	            	expected: basic.snapshot{namespaces:map[types.UID]string{"349a6874-53e2-494b-bebe-80214c7f0a4d":"k0s-autopilot", "3aeba8f2-b3b7-4add-949e-960c7fcc0adf":"default", "5bbb4d2c-4385-4c8c-858b-ec9627bd5796":"kube-node-lease", "8f548b8e-35f6-4aa7-9be7-6c4379fe2717":"kube-system", "e5334b33-5ac9-42db-a40c-b6fedf91a3b3":"kube-public"}, services:map[types.UID]string{"778a140d-3463-4771-b110-0fa24b13b09e":"kubernetes"}, nodes:map[types.UID]string{"3eed4a96-7c27-4787-99b9-dab3cdfe1868":"controller0", "9a67d557-7a95-4120-a220-7aa770c4bfc7":"worker1", "f0023560-6137-495d-bdc1-9123fa3f814f":"worker0"}}
        	            	actual  : basic.snapshot{namespaces:map[types.UID]string{"349a6874-53e2-494b-bebe-80214c7f0a4d":"k0s-autopilot", "3aeba8f2-b3b7-4add-949e-960c7fcc0adf":"default", "5bbb4d2c-4385-4c8c-858b-ec9627bd5796":"kube-node-lease", "8f548b8e-35f6-4aa7-9be7-6c4379fe2717":"kube-system", "e5334b33-5ac9-42db-a40c-b6fedf91a3b3":"kube-public"}, services:map[types.UID]string{"778a140d-3463-4771-b110-0fa24b13b09e":"kubernetes"}, nodes:map[types.UID]string{"3eed4a96-7c27-4787-99b9-dab3cdfe1868":"controller0", "9a67d557-7a95-4120-a220-7aa770c4bfc7":"worker1", "bc212010-9d65-4bc3-843a-03c20be355e3":"controller1", "f0023560-6137-495d-bdc1-9123fa3f814f":"worker0"}}

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -11,5 +11,6 @@
        	            	  },
        	            	- nodes: (map[types.UID]string) (len=3) {
        	            	+ nodes: (map[types.UID]string) (len=4) {
        	            	   (types.UID) (len=36) "3eed4a96-7c27-4787-99b9-dab3cdfe1868": (string) (len=11) "controller0",
        	            	   (types.UID) (len=36) "9a67d557-7a95-4120-a220-7aa770c4bfc7": (string) (len=7) "worker1",
        	            	+  (types.UID) (len=36) "bc212010-9d65-4bc3-843a-03c20be355e3": (string) (len=11) "controller1",
        	            	   (types.UID) (len=36) "f0023560-6137-495d-bdc1-9123fa3f814f": (string) (len=7) "worker0"
        	Test:       	TestBackupSuite/TestK0sGetsUp

Fixes: b97739bb8 ("Support variable controller/worker counts in backup inttest")
Signed-off-by: Tom Wieczorek <twieczorek@mirantis.com>