Don't check for dynamic config when listing images
There's no --enable-dynamic-config flag for k0s airgap list-images:

$ k0s airgap list-images --enable-dynamic-config
Error: unknown flag: --enable-dynamic-config

Fixes: 1e5e6b6e5 ("Disable airgap list-images for dynamic config")
Signed-off-by: Tom Wieczorek <twieczorek@mirantis.com>