Fix health prober unit test flakes
Use synctest to make event collection deterministic.

Addresses test failures like this:

--- FAIL: TestEvents (0.03s)
    --- FAIL: TestEvents/prober_collects_emitted_events (0.01s)
        events_test.go:46:
            	Error Trace:	/Users/runner/work/k0s/k0s/pkg/component/prober/events_test.go:46
            	Error:      	"[]" should have 3 item(s), but has 0
            	Test:       	TestEvents/prober_collects_emitted_events
            	Messages:   	should have 3 events in the state due to ring buffer size
        events_test.go:47:
            	Error Trace:	/Users/runner/work/k0s/k0s/pkg/component/prober/events_test.go:47
            	Error:      	Not equal:
            	            	expected: []prober.Event{prober.Event{At:time.Date(2026, time.January, 9, 14, 32, 58, 893670000, time.Local), Message:"Test event 2", Payload:interface {}(nil)}, prober.Event{At:time.Date(2026, time.January, 9, 14, 32, 58, 893670000, time.Local), Message:"Test event 3", Payload:interface {}(nil)}, prober.Event{At:time.Date(2026, time.January, 9, 14, 32, 58, 893670000, time.Local), Message:"Test event 4", Payload:interface {}(nil)}}
            	            	actual  : []prober.Event{}

            	            	Diff:
            	            	--- Expected
            	            	+++ Actual
            	            	@@ -1,53 +1,2 @@
            	            	-([]prober.Event) (len=3) {
            	            	- (prober.Event) {
            	            	-  At: (time.Time) {
            	            	-   wall: (uint64) 14001799297323258480,
            	            	-   ext: (int64) 4064418,
            	            	-   loc: (*time.Location)({
            	            	-    name: (string) "",
            	            	-    zone: ([]time.zone) <nil>,
            	            	-    tx: ([]time.zoneTrans) <nil>,
            	            	-    extend: (string) "",
            	            	-    cacheStart: (int64) 0,
            	            	-    cacheEnd: (int64) 0,
            	            	-    cacheZone: (*time.zone)(<nil>)
            	            	-   })
            	            	-  },
            	            	-  Message: (string) (len=12) "Test event 2",
            	            	-  Payload: (interface {}) <nil>
            	            	- },
            	            	- (prober.Event) {
            	            	-  At: (time.Time) {
            	            	-   wall: (uint64) 14001799297323258480,
            	            	-   ext: (int64) 4064585,
            	            	-   loc: (*time.Location)({
            	            	-    name: (string) "",
            	            	-    zone: ([]time.zone) <nil>,
            	            	-    tx: ([]time.zoneTrans) <nil>,
            	            	-    extend: (string) "",
            	            	-    cacheStart: (int64) 0,
            	            	-    cacheEnd: (int64) 0,
            	            	-    cacheZone: (*time.zone)(<nil>)
            	            	-   })
            	            	-  },
            	            	-  Message: (string) (len=12) "Test event 3",
            	            	-  Payload: (interface {}) <nil>
            	            	- },
            	            	- (prober.Event) {
            	            	-  At: (time.Time) {
            	            	-   wall: (uint64) 14001799297323258480,
            	            	-   ext: (int64) 4064668,
            	            	-   loc: (*time.Location)({
            	            	-    name: (string) "",
            	            	-    zone: ([]time.zone) <nil>,
            	            	-    tx: ([]time.zoneTrans) <nil>,
            	            	-    extend: (string) "",
            	            	-    cacheStart: (int64) 0,
            	            	-    cacheEnd: (int64) 0,
            	            	-    cacheZone: (*time.zone)(<nil>)
            	            	-   })
            	            	-  },
            	            	-  Message: (string) (len=12) "Test event 4",
            	            	-  Payload: (interface {}) <nil>
            	            	- }
            	            	+([]prober.Event) {
            	            	 }
            	Test:       	TestEvents/prober_collects_emitted_events
            	Messages:   	should have 3 last events in the state due to ring buffer size
FAIL

Signed-off-by: Tom Wieczorek <twieczorek@mirantis.com>