Stabilize health prober tests by flushing pending ticks
The prober tests relied on sleeping for exactly N intervals and then
canceling, which could interfere with the final ticker tick. Calls
synctest.Wait after sleeping to ensure that any queued ticker callbacks
are processed before canceling the context.

Fixes test failures like these:

--- FAIL: TestHealthChecks (0.00s)
    --- FAIL: TestHealthChecks/prober_stores_and_overrides_error_results (0.00s)
        prober_test.go:58:
            	Error Trace:	/go/src/github.com/k0sproject/k0s/pkg/component/prober/prober_test.go:58
            	Error:      	An error is expected but got nil.
            	Test:       	TestHealthChecks/prober_stores_and_overrides_error_results
            	Messages:   	should have error in the first result for component `test`
        prober_test.go:59:
            	Error Trace:	/go/src/github.com/k0sproject/k0s/pkg/component/prober/prober_test.go:59
            	Error:      	Received unexpected error:
            	            	test2 error
            	Test:       	TestHealthChecks/prober_stores_and_overrides_error_results
            	Messages:   	should have no errors for component `test2`
        prober_test.go:63:
            	Error Trace:	/go/src/github.com/k0sproject/k0s/pkg/component/prober/prober_test.go:63
            	Error:      	An error is expected but got nil.
            	Test:       	TestHealthChecks/prober_stores_and_overrides_error_results
            	Messages:   	should have error in the last result for component `test3`
FAIL
FAIL	github.com/k0sproject/k0s/pkg/component/prober	0.018s

Fixes: 23fc9d821 ("Fix health prober unit test flakes")
Signed-off-by: Tom Wieczorek <twieczorek@mirantis.com>