Start listening before starting the serving goroutine
This ensures that the socket is open before the tests are executed.
Prevents test races like the following:

--- FAIL: TestGetNodename (0.01s)
    --- FAIL: TestGetNodename/windows_metadata_service_is_available (0.00s)
        nodehostname_test.go:65:
            	Error Trace:	/go/src/github.com/k0sproject/k0s/pkg/node/nodehostname_test.go:65
            	Error:      	Should not be: "6471c247ef83"
            	Test:       	TestGetNodename/windows_metadata_service_is_available
FAIL

Signed-off-by: Tom Wieczorek <twieczorek@mirantis.com>
(cherry picked from commit 8246ca9f6e2da63062a1918b79751543fd61b6c6)
(cherry picked from commit b8002e689b574c42a91335cf050ed542f28e2f3a)
(cherry picked from commit bb7010c669eaee2f5b226a288a010b70895fa95c)